services:
  frontend:
    build:
      context: .
    container_name: collacode-frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT_INT}
    networks:
      - collacode-network
    volumes:
      - collacode-media-backup:/home/app/dist/media
      - collacode-media:/home/app/public/media
  backend:
    build:
      context: backend
      args:
        INIT_ADMIN_NAME: ${INIT_ADMIN_NAME}
        INIT_ADMIN_PW: ${INIT_ADMIN_PW}
        BACKEND_PORT_INT: ${BACKEND_PORT_INT}
    container_name: collacode-backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT_INT}
    environment:
      - BACKEND_PORT_INT=${BACKEND_PORT_INT}
    networks:
      - collacode-network
    volumes:
      - collacode-media-backup:/home/app/dist/media
      - collacode-media:/home/app/public/media
      - collacode-data:/home/app/backend/data

volumes:
  collacode-data:
  collacode-media:
  collacode-media-backup:

networks:
  collacode-network:
    driver: bridge