DATABASE_PATH = "data.db"
CROWD_DATABASE_PATH = "crowd.db"
TEASER_PATH = "media/teaser"
EVIDENCE_PATH = "media/evidence"

SECRET_KEY = "SECRRET_KEY"
DEBUG = False
MAX_CONTENT_LENGTH = 5 * 1024 * 1024
SESSION_COOKIE_DOMAIN = "SESSION_COOKIE_DOMAIN"
REMEMBER_COOKIE_PATH = "REMEMBER_COOKIE_PATH"
REMEMBER_COOKIE_DOMAIN = "REMEMBER_COOKIE_DOMAIN"
REMEMBER_COOKIE_SECURE = False
BP_PREFIX = ""