name: collacode
dependencies:
  - python=3.12
  - flask
  - flask-cors
  - flask-login
  - numpy
  - pandas
  - requests
  - waitress
  - python-dotenv
  - validators
  - scikit-learn
  - pillow
  - pip:
    - argon2-cffi
    - caribou
    - krippendorff
