BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "game_expertise" (
	"id"	INTEGER NOT NULL UNIQUE,
	"game_id"	INTEGER NOT NULL,
	"user_id"	INTEGER NOT NULL,
	"value"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT) ON CONFLICT REPLACE,
	FOREIGN KEY("game_id") REFERENCES "games"("id") ON DELETE CASCADE,
	FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);
COMMIT;
