BEGIN TRANSACTION;
DROP TABLE IF EXISTS "logs";
CREATE TABLE "logs" (
	"id"	INTEGER NOT NULL UNIQUE,
	"user_id"	INTEGER,
	"timestamp"	INTEGER NOT NULL,
	"action"	TEXT NOT NULL,
	"data"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE SET NULL
);

DROP TABLE IF EXISTS "update_times";
CREATE TABLE "update_times" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"timestamp"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
