TBL_DATASETS = "datasets"
TBL_USERS = "users"
TBL_PRJ_USERS = "project_users"
TBL_ITEMS = "items"
TBL_CODES = "codes"
TBL_TRANS = "code_transitions"
TBL_TAGS = "tags"
TBL_TAG_ASS = "tag_assignments"
TBL_DATATAGS = "datatags"
TBL_EVIDENCE = "evidence"
TBL_EXPERTISE = "expertise"
TBL_META_GROUPS = "meta_groups"
TBL_META_ITEMS = "meta_items"
TBL_META_CATS = "meta_categories"
TBL_META_AG = "meta_agreements"
TBL_META_CON_CAT = "meta_cat_connections"
TBL_META_CON_TAG = "meta_tag_connections"
TBL_META_CON_EV = "meta_ev_connections"

TBL_OBJECT = "objections"

TBL_SCORES = "game_scores"
TBL_SCORES_ITEMS = "game_scores_items"
TBL_SCORES_TAGS = "game_scores_tags"

TBL_LOGS = "logs"
TBL_UPDATES = "update_times"

C_TBL_BLOCKD = "blocked_items"
C_TBL_CLIENT = "client_info"
C_TBL_COUNTS = "item_sim_counts"
C_TBL_SUBS = "submissions"
C_TBL_SIMS = "item_sims"
C_TBL_USERS = "user_guids"
C_TBL_FEED = "feedback"
C_TBL_RATINGS = "ratings"
C_TBL_INTS = "interaction_logs"
